- name: configure databaseserver
  hosts: db
  become: yes
  vars:
    login_host: db.daws78s.fun
  tasks:
  - name: install mysql 
    ansible.builtin.dnf:
      name: mysql-server
      state: latest

  - name: Start and enable the server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes 

  #check password is setup or not
  - name: check DB connection
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "{{ login_host }}"
      filter: version
    ignore_errors: yes
    register: mysql_connection_output

  - name: print output
    ansible.builtin.debug:
      msg: "Output: {{ mysql_connection_output }}"    