- name: configure frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.dnf: 
      name: nginx
      state: latest

  - name: Enable and start nginx
    ansible.builtin.service:
      name: nginx
      State: started
      enabled: yes

  - name: delete default website
    ansible.builtin.file:
      path: /usr/share/nginx/html/*
      state: absent    

  - name: Download the file
    ansible.builtin.get_url:
      path: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
